import {cleanName,cleanMobile,makeStudents} from './data-quality-core.js';
const $=id=>document.getElementById(id);let students=makeStudents(),position=0,running=false,paused=false,resumeWait,drafts=[];
function render(){const body=$('students');body.replaceChildren();students.forEach((s,i)=>{const tr=document.createElement('tr');tr.id=`row-${i}`;tr.className=s.status==='Corrected'?'done':s.status==='Needs mobile review'?'review':'';[s.id,s.surname,s.forename,s.dob,s.address,s.mobile,s.status].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)});$('progress').value=position;}
function audit(text){const li=document.createElement('li');li.textContent=text;$('audit').prepend(li);}
function status(text){$('status').textContent=text;$('field-action').textContent=text;}
async function beat(){await new Promise(r=>setTimeout(r,Number($('speed').value)));if(paused)await new Promise(r=>resumeWait=r);}
function buttons(){ $('run').disabled=running||position===20;$('next').disabled=running||position===20;$('reset').disabled=running;$('pause').disabled=!running;}
function show(s){$('record').hidden=false;$('record-name').textContent=s.id;for(const [id,value] of Object.entries({ref:s.id,forename:s.forename,surname:s.surname,known:s.forename.trim(),'known-surname':s.surname.trim(),address:s.address,mobile:s.mobile,email:s.email})){$(id).value=value;$(id).className='';}}
async function correct(id,before,after,next){const f=$(id);f.focus({preventScroll:true});f.className=before===after?'fixed':'bad';status(`${id}: ${before===after?'already correct':'red highlight — correction needed'}`);await beat();if(before!==after){f.value=after;$(next).focus({preventScroll:true});f.className='fixed';status(`Tab: ${id} normalised`);audit(`${students[position].id} ${id}: ${JSON.stringify(before)} → ${JSON.stringify(after)} (Tab)`);await beat();}return after;}
async function one(){const s=students[position];const row=$(`row-${position}`);row.className='active';row.parentElement.parentElement.parentElement.scrollTop=Math.max(0,row.offsetTop-180);status(`Opening ${s.id} — student ${position+1} of 20`);await beat();show(s);await beat();
s.forename=await correct('forename',s.forename,cleanName(s.forename),'surname');s.surname=await correct('surname',s.surname,cleanName(s.surname),'mobile');const m=cleanMobile(s.mobile);s.mobile=await correct('mobile',s.mobile,m.value,'email');
if(!m.valid){$('mobile').className='review';$('email').className='bad';$('email').focus({preventScroll:true});status('12-digit mobile — highlight email and open AutoEmail');await beat();$('autoemail').hidden=false;$('email-to').value=s.email;$('email-body').value=`Hello ${s.forename},\n\nPlease confirm your correct 11-digit mobile number. The number in this synthetic record has 12 digits.\n\nThank you,\nStudent Records (demonstration)`;drafts.push({id:s.id,email:s.email,body:$('email-body').value});renderDrafts();audit(`${s.id}: AutoEmail draft prepared for ${s.email}; nothing sent.`);await beat();await beat();$('keep-draft').classList.add('target');status('Retain AutoEmail draft for staff review (simulation)');await beat();$('autoemail').hidden=true;$('keep-draft').classList.remove('target');s.status='Needs mobile review';}else s.status='Corrected';
$('save').classList.add('target');status(`${s.id}: Save & Close — simulated local update`);await beat();$('record').hidden=true;$('save').classList.remove('target');position++;render();audit(`${s.id}: Save & Close complete. ${s.status}.`);await beat();}
async function run(all){if(running||position===20)return;running=true;buttons();try{do{await one();}while(all&&position<20);status(position===20?'Complete — 20 checked; 4 mobile exceptions; 4 drafts; 0 emails sent':`${position}/20 checked — ready for next student`);}finally{running=false;paused=false;$('pause').textContent='Pause';buttons();renderDrafts();}}
$('run').onclick=()=>run(true);$('next').onclick=()=>run(false);$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause';if(!paused&&resumeWait){resumeWait();resumeWait=null;}status(paused?'Paused — resume to continue':'Resuming');};$('reset').onclick=()=>{students=makeStudents();position=0;$('record').hidden=true;$('autoemail').hidden=true;$('audit').replaceChildren();drafts=[];renderDrafts();render();buttons();status('Ready — 20 students');};render();buttons();

function renderDrafts(){const holder=$('drafts');holder.replaceChildren();drafts.forEach(d=>{const b=document.createElement('button');b.textContent=d.id+' draft';b.disabled=running;b.onclick=()=>{$('email-to').value=d.email;$('email-body').value=d.body;$('autoemail').hidden=false;$('keep-draft').disabled=false;};holder.append(b);});}
$('keep-draft').onclick=()=>{if(!running){$('autoemail').hidden=true;$('keep-draft').disabled=true;}};
